# Generated by Django 6.1.1 on 2026-09-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('sql', models.TextField(help_text='Solo SELECT. Usa %(id_cliente)s como parametro si aplica.')),
                ('visualizacion', models.CharField(choices=[('tabla', 'Tabla'), ('dona', 'Dona'), ('barras', 'Barras')], default='tabla', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'consulta SQL',
                'verbose_name_plural': 'consultas SQL',
                'ordering': ['nombre'],
            },
        ),
    ]
